### ISSUE TITLE
Improper Specificity Calculations

### ISSUE THREAD

**Issue by thejase** [pocketjoso/specificity-graph#26]
Referencing this line: https://github.com/pocketjoso/specificity-graph/blob/master/lib/generateCssData.js#L10

Unfortunately, specificity is not an additive calculation.  Each `spec` (e.g. IDs, classes, tags) lives in it's own infinite-based dimension, meaning you cannot take an `#foo .bar` and simply say it's specificity is `100 + 10 = 110`.

Take for example:

```
<div id="id-hook" class="class-hook">
    This should be red if 11 classes win or blue if one ID wins.
</div>

<style>
div {
  display: flex;
  color: #fff;
  min-height: 4em;
  vertical-align: middle;
  align-items: center;
  justify-content: center;
}

#id-hook { /* 1 ID * 100 = 100 */
  background-color: blue;
}

.class-hook.class-hook.class-hook.class-hook.class-hook.class-hook.class-hook.class-hook.class-hook.class-hook.class-hook { /* 11 classes * 10 = 110 */
  background-color: red;
}
</style>
```

According to your calculations, the `#id-hook` selector should have lower specificity than the `.class-hook...` selector.  In reality, the ID selector will always be higher in specificity to any other selector that only has lower-specificity aspects, no matter how many there are.

For more knowledge, this is an awesome read: https://css-tricks.com/css-specificity-is-base-infinite/

**Comment by pocketjoso** [comment]
I'm aware how CSS specificity works. The weights used are picked in order to provide a useful visualisation, that's correct most of the time. Really, if you're using 10+ nested items in your selectors then graph accuracy is going to be the least of your problems.

..if anything, I at least our issue to say that this should work documented in the README - care to create a PR? Unless you have an idea for a more correct visualisation.

Cheers

**Comment by pocketjoso** [comment]
Will close this due to inactivity - feel free to continue to comment!
